apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfoodapi-pedido-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfoodapi-pedido
  template:
    metadata:
      labels:
        app: fastfoodapi-pedido
    spec:
      containers:
        - name: fastfoodapi-pedido-pod
          image: rm359211/fastfood-pedido-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: FASTFOOD_JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: secret-config
                  key: FASTFOOD_JDBC_URL
            - name: FASTFOOD_DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret-config
                  key: FASTFOOD_DB_USER
            - name: FASTFOOD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-config
                  key: FASTFOOD_DB_PASSWORD
          resources:
            requests:
              cpu: 1m
