volumes:
  postgresql_data: {}

services:
  fastfood_app:
    image: fastfood-pedido-app:1
    ports:
      - "8080:8080"
    restart: always
    environment:
      FASTFOOD_DB_HOST: jdbc:postgresql://fastfood-db.cwurub6uddjh.us-east-1.rds.amazonaws.com:5432
      FASTFOOD_DB_USER: postgres
      FASTFOOD_DB_PASSWORD: 1234
      FASTFOOD_DB_NAME: fastfood
