spring:
  application:
    name: pedido
  datasource:
    url: ${FASTFOOD_JDBC_URL}
    username: ${FASTFOOD_DB_USER}
    password: ${FASTFOOD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
external:
  api:
    url: http://localhost:8080/
    pagamento:
      url: http://18.204.157.147:30001/
    producao:
      url: http://18.204.157.147:30002/fastfood-producao
      path:
        post: "/pedido"
        patch: "/pedido/{id}/status/{statusPedido}"
server:
  servlet:
    context-path: /fastfood